### ISSUE TITLE
css selector #kkaufman h1, h2, h3, h4, h5, h6 {} is overriding into other personal pages

### ISSUE THREAD

**Issue by lwmatysik** [bhogancvtc/website#1]

**Comment by lwmatysik** [comment]
to fix:
#kkaufman h1, #kkaufman h2, #kkaufman h3, #kkaufman h4, #kkaufman h5, #kkaufman h6 {}

**Comment by Miah747** [comment]
_Suggestion for kkaufman_: I would just make that a class instead of targeting that many elements by drilling down from the body id over and over. What _lwmatysic_ suggested above is fine too, I just think it might be better to handle it with a class. Either option below works, but the second is more specific than the first:

``` css
.kkaufman_headings{

}
```

-or-

``` css
#kkaufman .kkaufman_headings{

}
```
